# Generated by Django 6.0.6 on 2026-07-11 07:49

import codex.models.fields
from django.conf import settings
from django.db import migrations, models

from codex.settings.config import get_bool, get_str


def seed_oidc_settings(apps, _schema_editor):
    """
    Create the OIDCSettings singleton.

    One-time courtesy import of any ``[auth.oidc]`` TOML keys from the
    pre-GUI config era (the section was never in a release, but a test
    deployment may have used it). Falls back to model defaults.
    """
    config = getattr(settings, "CODEX_CONFIG", {})
    oidc_settings = apps.get_model("codex", "OIDCSettings")
    oidc_settings.objects.get_or_create(
        pk=1,
        defaults={
            "enabled": get_bool(config, "auth.oidc.enabled", default=False),
            "provider_name": get_str(config, "auth.oidc.provider_name", default="SSO"),
            "server_url": get_str(config, "auth.oidc.server_url", default=""),
            "client_id": get_str(config, "auth.oidc.client_id", default=""),
            "client_secret": get_str(config, "auth.oidc.client_secret", default=""),
            "scope": get_str(
                config, "auth.oidc.scope", default="openid profile email"
            ),
            "pkce": get_bool(config, "auth.oidc.pkce", default=True),
            "token_auth_method": get_str(
                config, "auth.oidc.token_auth_method", default=""
            ),
            "fetch_userinfo": get_bool(
                config, "auth.oidc.fetch_userinfo", default=True
            ),
            "username_claim": get_str(
                config, "auth.oidc.username_claim", default="preferred_username"
            ),
            "create_users": get_bool(config, "auth.oidc.create_users", default=True),
            "link_by_email": get_bool(
                config, "auth.oidc.link_by_email", default=False
            ),
            "sync_groups": get_bool(config, "auth.oidc.sync_groups", default=False),
            "groups_claim": get_str(config, "auth.oidc.groups_claim", default="groups"),
            "admin_group": get_str(config, "auth.oidc.admin_group", default=""),
            "rp_initiated_logout": get_bool(
                config, "auth.oidc.rp_initiated_logout", default=False
            ),
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0046_comicboxtaggingdefaults_rename_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='OIDCSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False)),
                ('provider_name', models.CharField(blank=True, default='SSO', max_length=128)),
                ('server_url', models.URLField(blank=True, default='', max_length=512)),
                ('client_id', models.CharField(blank=True, default='', max_length=128)),
                ('client_secret', codex.models.fields.EncryptedCharField(blank=True, default='', max_length=512)),
                ('scope', models.CharField(blank=True, default='openid profile email', max_length=128)),
                ('pkce', models.BooleanField(default=True)),
                ('token_auth_method', models.CharField(blank=True, default='', max_length=128)),
                ('fetch_userinfo', models.BooleanField(default=True)),
                ('username_claim', models.CharField(blank=True, default='preferred_username', max_length=128)),
                ('create_users', models.BooleanField(default=True)),
                ('link_by_email', models.BooleanField(default=False)),
                ('sync_groups', models.BooleanField(default=False)),
                ('groups_claim', models.CharField(blank=True, default='groups', max_length=128)),
                ('admin_group', models.CharField(blank=True, default='', max_length=128)),
                ('rp_initiated_logout', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'OIDCSettings',
                'get_latest_by': 'updated_at',
                'abstract': False,
            },
        ),
        migrations.RunPython(
            code=seed_oidc_settings,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
